services:
  postgres:
    image: postgres:16
    container_name: book-management-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: book_management
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: