spring:
  application:
    name: book-management-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/book_management}
    username: ${DB_USER:app}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

  jooq:
    sql-dialect: postgres